# Generated by Django 6.0.3 on 2026-05-13 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='lead',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'circle_lead'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_circles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='circle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.circle'),
        ),
        migrations.AddField(
            model_name='user',
            name='occupancy_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
